id: IEB825026
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T14:07:46+00:00'
last_modified: '2022-06-09T17:48:58.908060+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC227
  title: 'ཆོས་རྒྱལ་རབ་བརྟན་ཀུན་བཟང་འཕགས་ཀྱི་རྣམ་ཐར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4F43:
      image_group_id: I2PD18725
      title: Volume 1 of chos rgyal rab brtan kun bzang 'phags kyi rnam thar/
      total_pages: 314
      order: 1
      base_file: 4F43.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
